services:
  db:
    image: mysql:5.7
    container_name: my-mysql
    environment:
      - TZ=Asia/Shanghai  # 设置容器时区
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_TIMEZONE=Asia/Shanghai  # 显式设置 MySQL 时区
    volumes:
      - /etc/timezone:/etc/timezone:ro  # 挂载主机时区配置
      - /etc/localtime:/etc/localtime:ro  # 挂载主机时区配置
      #      - db_data:/var/lib/mysql  # 将数据挂载到命名卷
      - D:/mysql_data:/var/lib/mysql  # 将数据挂载到命名卷
    ports:
      - "3306:3306"

volumes:
  db_data:
